### ISSUE TITLE
Fix Ghost Elements

### ISSUE THREAD

**Issue by bruh1273** [Mikarific/InfiniteCraftHelper#1]
If you have played the game for a fair amount of time, you may have noticed that when you click elements in rapid succession, that sometimes it will bug out the element and leave a permanent, unmovable element on your screen, that only goes away when you sweep the board.
My suggestion is that you can fix that visual bug from happening.
(Image for reference on what I'm talking about)
https://imgur.com/6lJ41tC

**Comment by Mikarific** [comment]
This was actually a problem in *Neal*'s code, and he's fixed this now after we reported this to him!
It happened when you double clicked an element to duplicate it while it was overlapping something that couldn't combine with it.
