### ISSUE TITLE
[ Suggestion ] Pinned elements should follow as you scroll.

### ISSUE THREAD

**Issue by oofcoder1** [Mikarific/InfiniteCraftHelper#4]
The elements you pin should follow as you scroll through the elements box.

**Comment by Mikarific** [comment]
Before implementing this feature, I actually had a talk with active people in the Infinite Craft discord server, and asked whether pinned elements should follow as you scroll. We settled on "it probably shouldn't".

We now have people with pinned element lists so long that they take up their entire sidebar, and implementing this would render their sidebar unusable. I think it was the right call.
