### ISSUE TITLE
Recipe Not Crafting

### ISSUE THREAD

**Issue by SomeH4CK3R** [Mikarific/InfiniteCraftHelper#7]
i am right clicking on my crafts and it says "i dont know how to craft this"

**Comment by Mikarific** [comment]
Infinite Craft Helper cannot time travel and does not know how you made things before you installed it, as the game does not store this information.

**Comment by Jeremy5909** [comment]
there's no way to get around this - is there? will recrafting it work or can we give it [this](https://infinibrowser.zptr.cc/search) database or something?
